version: '3.1'

services:

  db:
    image: postgres
    restart: always
    volumes:
     - ./db:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"

  web:
    image: node:alpine
    depends_on:
      - db
    restart: always
    command: yarn start
    working_dir: /usr/src
    environment:
      NODE_ENV: ${NODE_ENV}
    volumes:
      - .:/usr/src
      - /usr/src/node_modules/
      - /usr/src/db/
    ports:
      - "4000:4000"
